export enum ContactType {
  CLIENTE = "CLIENTE",
  RECOMENDACION = "RECOMENDACION",
  FACEBOOK = "FACEBOOK",
  INSTAGRAM = "INSTAGRAM",
  TIKTOK = "TIKTOK",
  YOUTUBE = "YOUTUBE",
  GOOGLE = "GOOGLE",
}
